# CloudFormation template to create an S3 bucket for CI/CD pull request testing
AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create an S3 bucket for CI/CD pull request"

Parameters: # Define a parameter for the environment (test, staging, production)
    Environment: 
        Type: String
        Default: test
        AllowedValues: 
          - test 
          - staging
          - production 

Resources: # Define the S3 bucket resource with tags for environment and GitHub Actions testing
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Environment
          Value: GitHubActionsTesting

Outputs: # Output the name of the created S3 bucket for reference in the pull request comments
  BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
